### ISSUE TITLE
compilation error VBA : batchfilescommon.appdrawer, errorh

### ISSUE THREAD

**Issue by Nicolas2067** [PacketSlayer/MSAccess-Form-Scaling#3]
Hello
thanks for your modules, but I can't compile in MS Access (Access pour Microsoft 365 MSO v 2410 Build 16.0.18129.20158 32 bits), and therefore cannot test.

compilation stop at
    Call errorh.errorhandler, which I suppose is a common error management (as I already have)
    batchfilescommon.appdrawer, which I cannot imagine what it is...*

thank you

**Comment by PacketSlayer** [comment]
Should be fixed now. That was reference to another module in another project. I removed references to it and it now should compile
